"""Product model edit

Revision ID: 1dc4bcf22fe3
Revises: cc943b23a236
Create Date: 2026-03-02 21:51:17.634916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc4bcf22fe3'
down_revision: Union[str, Sequence[str], None] = 'cc943b23a236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'orders', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
